ACTIVITY_NETWORKING = 'networking'
ACTIVITY_DEPLOYING = 'deploying'
ACTIVITY_REBOOTING = 'rebooting'
ACTIVITY_POWERING_OFF = 'powering - off'
ACTIVITY_RUNNING_BOOT_SCRIPT = 'running_boot_script'
ACTIVITY_SUSPENDING = 'suspending'
ACTIVITY_POWERING_ON = 'powering - on'
ACTIVITY_RESUMING = 'resuming'
ACTIVITY_SCHEDULING = 'scheduling'
ACTIVITY_INITIALIZING = 'initializing'
ACTIVITY_SPAWNING = 'spawning'
ACTIVITY_REBOOTING_HARD = 'rebooting_hard'
ACTIVITY_DEPLOY_ERROR = 'deploy_error'
ACTIVITY_EMPTY = ''
STATUS_PAUSED = 'paused'
STATUS_DEPLOY_ERROR = 'deploy_error'
STATUS_NETWORKING = 'networking'
STATUS_DEPLOYING = 'deploying'
STATUS_DELETED = 'deleted'
STATUS_REBOOT = 'reboot'
STATUS_MIGRATING = 'migrating'
STATUS_RESCUE = 'rescue'
STATUS_ERROR = 'error'
STATUS_VERIFY_RESIZE = 'verify_resize'
STATUS_RESIZE = 'resize'
STATUS_HARD_REBOOT = 'hard_reboot'
STATUS_SHUTOFF = 'shutoff'
STATUS_SUSPENDED = 'suspended'
STATUS_SHUTTING_DOWN = 'shutting - down'
STATUS_TERMINATED = 'terminated'
STATUS_RUNNING = 'running'
STATUS_PENDING = 'pending'
STATUS_BUILD = 'build'
STATUS_ACTIVE = 'active'
STATUS_UNKNOWN = 'unknown'
INSTANCE_STATUSES = (
    STATUS_ACTIVE,
    STATUS_BUILD,
    STATUS_PENDING,
    STATUS_RUNNING,
    STATUS_TERMINATED,
    STATUS_SHUTTING_DOWN,
    STATUS_SUSPENDED,
    STATUS_SHUTOFF,
    STATUS_HARD_REBOOT,
    STATUS_RESIZE,
    STATUS_VERIFY_RESIZE,
    STATUS_ERROR,
    STATUS_RESCUE,
    STATUS_MIGRATING,
    STATUS_REBOOT,
    STATUS_DELETED,
    STATUS_DEPLOYING,
    STATUS_NETWORKING,
    STATUS_DEPLOY_ERROR,
    STATUS_UNKNOWN,
    STATUS_PAUSED
)
INSTANCE_STATUS_ACTIVITIES = (
    ACTIVITY_EMPTY,
    ACTIVITY_DEPLOY_ERROR,
    ACTIVITY_REBOOTING_HARD,
    ACTIVITY_SPAWNING,
    ACTIVITY_INITIALIZING,
    ACTIVITY_SCHEDULING,
    ACTIVITY_RESUMING,
    ACTIVITY_POWERING_ON,
    ACTIVITY_SUSPENDING,
    ACTIVITY_RUNNING_BOOT_SCRIPT,
    ACTIVITY_POWERING_OFF,
    ACTIVITY_REBOOTING,
    ACTIVITY_DEPLOYING,
    ACTIVITY_NETWORKING
)